server:
  port: 8083
spring:
  redis:
    host: 59.110.243.130
  rabbitmq:
    host: 59.110.243.130
    username: guest
    password: guest
    port: 5672
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 59.110.243.130:9300